---
name: Release Windows
'on':
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2025
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-libadwaita
            mingw-w64-x86_64-poppler
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-meson
            base-devel

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-msvc
          targets: x86_64-pc-windows-msvc

      - name: Install Inno Setup
        shell: pwsh
        run: |
          winget install --force --id JRSoftware.InnoSetup --exact --version 6.4.3 `
            --accept-package-agreements --accept-source-agreements --disable-interactivity --scope machine

      - name: Set installer name
        shell: bash
        run: |
          echo "name=rnote-win-installer-$(echo ${GITHUB_REF_NAME#v} | sed -e 's/[^A-Za-z0-9._-]/_/g')-x86_64" >> $GITHUB_OUTPUT
        id: installer_name

      - name: Install Just
        shell: pwsh
        run: cargo install just --locked

      - name: Build
        shell: pwsh
        env:
          PKG_CONFIG_PATH: C:\msys64\mingw64\lib\pkgconfig
        run: |
          $env:PATH = "$env:PATH;C:\Program Files (x86)\Inno Setup 6"
          just ci=true prerequisites-win
          just ci=true setup-win-installer '${{ steps.installer_name.outputs.name }}'
          cargo build --release --target x86_64-pc-windows-msvc
          just ci=true build-win-installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rnote-win-installer
          path: _mesonbuild/${{ steps.installer_name.outputs.name }}.exe
          if-no-files-found: error
          compression-level: 0

      - name: Upload to release
        if: github.event_name == 'release'
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} _mesonbuild/${{ steps.installer_name.outputs.name }}.exe
